runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app --timeout 20000

endpoints_api_service:
  name: readpositive-298614.appspot.com
  rollout_strategy: managed

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  max_pending_latency: automatic
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 1.5
  disk_size_gb: 10

readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 24000
